import { ExternalLink } from "lucide-react";
import { useState } from "react";

import { LoadError } from "@/components/load-error";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

import type { PlaidEnv } from "@shared/api";

// SetupScreen is the first run: the two Plaid credentials and the
// environment. Everything else (tokens, the encryption key, the database)
// is generated by the main process when this is saved.
export function SetupScreen() {
  const [env, setEnv] = useState<PlaidEnv>("sandbox");
  const [clientId, setClientId] = useState("");
  const [secret, setSecret] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setError(null);
    try {
      await window.api.app.saveSetup({ plaidEnv: env, plaidClientId: clientId, plaidSecret: secret });
    } catch (err) {
      setError((err as Error).message.replace(/^Error invoking remote method '[^']+': Error: /, ""));
      setSaving(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center px-4 py-10">
      <div className="w-full max-w-2xl space-y-6">
        <div className="flex items-center gap-3">
          <div className="flex size-9 items-center justify-center rounded-md bg-primary text-sm font-semibold text-primary-foreground">
            MI
          </div>
          <div>
            <h1 className="text-xl font-semibold tracking-tight">Welcome to Money Insighter</h1>
            <p className="text-sm text-muted-foreground">
              Your accounts and transactions, synced from Plaid into a database on this computer.
            </p>
          </div>
        </div>

        <form onSubmit={submit}>
          <Card>
            <CardHeader>
              <CardTitle>Plaid credentials</CardTitle>
              <CardDescription>
                Sign in at dashboard.plaid.com, open Developers → Keys, and copy the client ID and
                the secret for the environment you choose.
              </CardDescription>
            </CardHeader>
            <CardContent className="grid gap-5">
              <fieldset className="grid gap-2">
                <Label>Environment</Label>
                <div className="grid gap-2 sm:grid-cols-2">
                  {(
                    [
                      ["sandbox", "Sandbox", "Test banks and fake data. Start here."],
                      ["production", "Production", "Real banks. Needs Plaid's production access approval."],
                    ] as const
                  ).map(([value, label, hint]) => (
                    <label
                      key={value}
                      className={`flex cursor-pointer gap-3 rounded-md border p-3 text-sm ${env === value ? "border-primary bg-muted/60" : ""}`}
                    >
                      <input
                        type="radio"
                        name="env"
                        value={value}
                        checked={env === value}
                        onChange={() => setEnv(value)}
                        className="mt-0.5"
                      />
                      <span>
                        <span className="font-medium">{label}</span>
                        <br />
                        <span className="text-muted-foreground">{hint}</span>
                      </span>
                    </label>
                  ))}
                </div>
              </fieldset>
              <div className="grid gap-1.5">
                <Label htmlFor="clientId">Client ID</Label>
                <Input
                  id="clientId"
                  value={clientId}
                  onChange={(e) => setClientId(e.target.value)}
                  className="font-mono"
                  autoComplete="off"
                  spellCheck={false}
                  required
                />
              </div>
              <div className="grid gap-1.5">
                <Label htmlFor="secret">{env === "sandbox" ? "Sandbox" : "Production"} secret</Label>
                <Input
                  id="secret"
                  type="password"
                  value={secret}
                  onChange={(e) => setSecret(e.target.value)}
                  className="font-mono"
                  autoComplete="off"
                  required
                />
                <p className="text-xs text-muted-foreground">
                  The secret must match the environment above. It is stored in your operating
                  system's keychain and never leaves this computer except to reach Plaid.
                </p>
              </div>

              <div className="rounded-md bg-muted/60 p-3 text-sm text-muted-foreground">
                <p className="font-medium text-foreground">Nothing else to configure in the dashboard.</p>
                <p className="mt-1">
                  Banks are connected through Plaid's Hosted Link in your browser, so no redirect URI,
                  webhook URL or allowed origin needs to be registered. Canadian banks are covered by
                  the default country (CA); change it in Settings if you need others.
                </p>
              </div>

              {error && <LoadError what="setup" message={error} />}

              <div className="flex items-center justify-between gap-3">
                <Button
                  type="button"
                  variant="ghost"
                  onClick={() => window.api.app.openExternal("https://dashboard.plaid.com/developers/keys")}
                >
                  <ExternalLink />
                  Open the Plaid dashboard
                </Button>
                <Button type="submit" disabled={saving || !clientId || !secret}>
                  {saving ? "Starting…" : "Save and start"}
                </Button>
              </div>
            </CardContent>
          </Card>
        </form>
      </div>
    </div>
  );
}
